# OpenAgua to WaMDaM to WASH
# Serve new imported input data from OA into Excel then GDX through WaMDaM
#### By Adel M. Abdallah, Utah State University, Jan 2019

Execute the following cells by pressing `Shift-Enter`, or by pressing the play button <img style='display:inline;padding-bottom:15px' src='play-button.png'> on the toolbar above.

# 1. Import python libraries

In [14]:
# 1. Import python libraries 
### set the notebook mode to embed the figures within the cell

import sqlite3
import numpy as np
import pandas as pd
import getpass
from hs_restclient import HydroShare, HydroShareAuthBasic
import os

import plotly
plotly.__version__
import plotly.offline as offline
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
offline.init_notebook_mode(connected=True)
from plotly.offline import init_notebook_mode, iplot
from plotly.graph_objs import *

init_notebook_mode(connected=True)         # initiate notebook for offline plot
import sys
from shutil import copyfile

import os
import csv
from collections import OrderedDict
import sqlite3
import pandas as pd
import numpy as np
from IPython.display import display, Image, SVG, Math, YouTubeVideo
import urllib
import calendar

import sqlite3
import pandas as pd
# https://github.com/NREL/gdx-pandas
from IPython.display import display, Image, SVG, Math, YouTubeVideo
from openpyxl import load_workbook
# import gdxpds

# ! pip install gdxpds
# import gdxpds
# import gams
# from gams import *
#from ctypes import c_bool
print 'The needed Python libraries have been imported'

The needed Python libraries have been imported

# 2. Connect to the WaMDaM SQLite on HydroShare
### Provide the HydroShare ID for your resource
Example  
https://www.hydroshare.org/resource/af71ef99a95e47a89101983f5ec6ad8b/

In [21]:
username = 'amabdallah'
password = 'MyHydroShareWorld'

auth = HydroShareAuthBasic(username=username, password=password)

hs = HydroShare(auth=auth)

print 'Connected to HydroShare'

# Then we can run queries against it within this notebook :)  
resource_url='https://www.hydroshare.org/resource/af71ef99a95e47a89101983f5ec6ad8b/' 


resource_id= resource_url.split("https://www.hydroshare.org/resource/",1)[1] 
resource_id=resource_id.replace('/','')

print resource_id

resource_md = hs.getSystemMetadata(resource_id)
# print resource_md
print 'Resource title'
print(resource_md['resource_title'])
print '----------------------------'

resources=hs.resource(resource_id).files.all()

file = ""

for f in hs.resource(resource_id).files.all():

    file += f.decode('utf8')

import json

file_json = json.loads(file)

for f in file_json["results"]:

    FileURL= f["url"]
    
    SQLiteFileName=FileURL.split("contents/",1)[1] 

cwd = os.getcwd()
print cwd
fpath = hs.getResourceFile(resource_id, SQLiteFileName, destination=cwd)
conn = sqlite3.connect(SQLiteFileName,timeout=10)

print 'done'
# Test if the connection works 
conn = sqlite3.connect(SQLiteFileName)

df = pd.read_sql_query("SELECT ResourceTypeAcronym   FROM ResourceTypes Limit 1 ", conn)
print df
                       
print '--------------------'                        
print '\n Connected to the WaMDaM SQLite file called'+': '+ SQLiteFileName

Connected to HydroShare
af71ef99a95e47a89101983f5ec6ad8b
Resource title
WEAP and WASH Bear River Systems Models
----------------------------
C:\Users\Adel\Documents\GitHub\WamdamProject\WaMDaM_JupyteNotebooks\2_VisualizePublish
done
  ResourceTypeAcronym
0                WEAP
--------------------

 Connected to the WaMDaM SQLite file called: Bear_River_WEAP_WASH.sqlite

# Query the seasonal data from WaMdaM into a dataframe

In [22]:
# The query has hard coded input parameters


# 2.2Identify_aggregate_TimeSeriesValues.csv
Query_UseCase_URL="""https://raw.githubusercontent.com/WamdamProject/WaMDaM_JupyterNotebooks/master/2_VisualizePublish/SQL_queries/WASH/Query_demand_seasonal.sql
"""

# Read the query text inside the URL
Query_UseCase_text = urllib.urlopen(Query_UseCase_URL).read()


# # return query result in a pandas data frame
df_Seasonal_WaMDaM= pd.read_sql_query(Query_UseCase_text, conn)


display (df_Seasonal_WaMDaM)

,ResourceTypeAcronym,ScenarioName,InstanceName,ObjectTypeCV,AttributeName,AttributeScale,AttributeNameCV,UnitName,SeasonName,SeasonNumericValue,SeasonOrder
0,WASH,ConsDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Jan,1.901533,1
1,WASH,ConsDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Feb,1.901533,2
2,WASH,ConsDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Mar,1.901533,3
3,WASH,ConsDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Apr,7.099911,4
4,WASH,ConsDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,May,7.099911,5
5,WASH,ConsDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Jun,7.099911,6
6,WASH,ConsDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Jul,7.099911,7
7,WASH,ConsDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Aug,7.099911,8
8,WASH,ConsDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Sep,7.099911,9
9,WASH,ConsDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Oct,7.099911,10
10,WASH,ConsDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Nov,1.901533,11
11,WASH,ConsDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Dec,1.901533,12
12,WASH,IncrDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Jan,2.852299,1
13,WASH,IncrDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Feb,2.852299,2
14,WASH,IncrDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Mar,2.852299,3
15,WASH,IncrDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Apr,10.64987,4
16,WASH,IncrDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,May,10.64987,5
17,WASH,IncrDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Jun,10.64987,6
18,WASH,IncrDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Jul,10.64987,7
19,WASH,IncrDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Aug,10.64987,8
20,WASH,IncrDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Sep,10.64987,9
21,WASH,IncrDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Oct,10.64987,10
22,WASH,IncrDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Nov,2.852299,11
23,WASH,IncrDemand,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Dec,2.852299,12
24,WASH,OneYear,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Jan,2.376916,1
25,WASH,OneYear,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Feb,2.376916,2
26,WASH,OneYear,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Mar,2.376916,3
27,WASH,OneYear,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Apr,8.874889,4
28,WASH,OneYear,j3,Demand site,dReqBase,1000000,Demand,cubic metre,May,8.874889,5
29,WASH,OneYear,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Jun,8.874889,6
30,WASH,OneYear,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Jul,8.874889,7
31,WASH,OneYear,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Aug,8.874889,8
32,WASH,OneYear,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Sep,8.874889,9
33,WASH,OneYear,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Oct,8.874889,10
34,WASH,OneYear,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Nov,2.376916,11
35,WASH,OneYear,j3,Demand site,dReqBase,1000000,Demand,cubic metre,Dec,2.376916,12

# Make copies of the origianl input file to the WASH Model

In [24]:

# Demand conservation file
copyfile("WASH_1yr_InputData_original.xlsx", "WASH_1yr_InputData_conserve.xlsx")

# Demand Increase file
copyfile("WASH_1yr_InputData_original.xlsx", "WASH_1yr_InputData_increase.xlsx")

# Preapre input data and write it to Excel input to WASH

In [25]:
Instance=df_Seasonal_WaMDaM['InstanceName'][1]
print Instance

column_name = ["ScenarioName"]
subsets = df_Seasonal_WaMDaM.groupby(column_name)

for subset in subsets.groups.keys():
    dt = subsets.get_group(name=subset)
    print subset
    
    df=dt.loc[:, 'SeasonName':'SeasonNumericValue'].T

    
    if subset=='ConsDemand':
        WASH_ExcelFile='WASH_1yr_InputData_conserve.xlsx'
        df=df.loc['SeasonNumericValue':, ]
        display(df)

    elif subset=='IncrDemand':
        WASH_ExcelFile='WASH_1yr_InputData_increase.xlsx' 
        
        df=df.loc['SeasonNumericValue':, ]
        columns = dict(map(reversed, enumerate(df.columns)))
        df = df.rename(columns=columns)
        df.head()
        display(df)
    else:
        continue

    sheetname='demandReq'
    #
    book = load_workbook(WASH_ExcelFile)

    UpdateDemand = book[sheetname]
    i =0
    for index, row in df.iterrows():
        for j, column in row.iteritems():
            UpdateDemand.cell(row=i+2, column=j+2, value=float(column))
        i += 1
    book.save(WASH_ExcelFile)

    print 'done writing the value to WASH excel file'

j3
ConsDemand

,0,1,2,3,4,5,6,7,8,9,10,11
SeasonNumericValue,1.901533,1.901533,1.901533,7.099911,7.099911,7.099911,7.099911,7.099911,7.099911,7.099911,1.901533,1.901533

done writing the value to WASH excel file
IncrDemand

,0,1,2,3,4,5,6,7,8,9,10,11
SeasonNumericValue,2.852299,2.852299,2.852299,10.64987,10.64987,10.64987,10.64987,10.64987,10.64987,10.64987,2.852299,2.852299

done writing the value to WASH excel file
OneYear

# Follow these steps to run the WASH Models in GAMS 

#### 1. Download and install [GAMS V.24.2.3](https://www.gams.com/) and have Excel 2007 onward
#####  You will need a license to run GAMS solvers.
 
#### 2. Open GAMS software. Go to File-> Project -> New Project. Navigate to the folder you created and create a new project file with any name you want.

#### 3. Double click on the gams file name: WASH-WaMDaM.gms to open the GAMS file

#### 4. Comment out the lines in 218-230 to choose one input file at a time. Then comment out the lines in 590-597 to write the results to the GDX file one at a time

# Read the WASH Area result objective function value from GDX

In [ ]:
gdx_files = {'Original':'C:\Users\Adel\Documents\GitHub\WEAP_WASH_OA\WASH-solution-original.gdx',
            'Conserve':'C:\Users\Adel\Documents\GitHub\WEAP_WASH_OA\WASH-solution-conserve.gdx',
            'Increase':'C:\Users\Adel\Documents\GitHub\WEAP_WASH_OA\WASH-solution-increase.gdx'}


for key,gdx_file in gdx_files.iteritems():
    with gdxpds.gdx.GdxFile(lazy_load=False) as f:
        f.read(gdx_file)
        for symbol in f:
            symbol_name = symbol.name
            if symbol_name=='Z':  
                df = symbol.dataframe
                Zvalue=str(df.iloc[0]['Level'])
                
                ZvalueApprox=float(Zvalue)

                print 'WASH Area for ' + key+'='+str(int(ZvalueApprox))

print '--------------------'

# Conserve_Original=Original-Conserve

# Increase_Original=Original-Conserve


print 'Results are replicated'

# The End :) Congratulations!

## The code below is part of the trial to run GAMS from here but didnt work for me. Feel free to give it a try

# Execute GAMS (Before and after update)
https://www.gams.com/latest/docs/API_PY_TUTORIAL.html

In [ ]:
import os
# os.path.dirname(os.path.abspath(__file__))

command="""start cmd cd C:\GAMS\win64/24.7 & gams.exe WASH-CEE6410"""

var=os.system(command)
print var

In [ ]:
from gams import *

In [ ]:
! conda install -c goop gams

In [ ]:
version = GamsWorkspace.api_version
print version
ws = GamsWorkspace('Test')
# ws = GamsWorkspace(debug=DebugLevel.KeepFiles)
print ws
job = ws.add_job_from_file("C:\Users\Adel\Documents\GitHub\WEAP_WASH_OA\WASH-CEE6410.gms")
job.run()
GamsDatabase = job.out_db

In [ ]:
ws = GamsWorkspace()
job = ws.add_job_from_file("C:\Users\Adel\Documents\GitHub\WEAP_WASH_OA\WASH-CEE6410.gms")
job.run()
GamsDatabase = job.out_db

In [ ]:
if len(sys.argv) > 1:
    ws = GamsWorkspace(system_directory = sys.argv[1])
else:
    ws = GamsWorkspace()

In [ ]:
GAMSWorkspace.GAMSWorkspace(workingDirectory = null,
systemDirectory = null,
DebugLevel  = DebugLevel.Off 
)